name: Testnet Deployment & Testing

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Manual trigger button
  schedule:
    - cron: '0 12 * * *' # Daily at noon UTC

jobs:
  testnet-tests:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[testnet]') || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Compile contracts
      run: npx hardhat compile
    
    - name: Test live contract functionality
      run: npx hardhat run scripts/test-live-contract.js --network bscTestnet
      env:
        PRIVATE_KEY: ${{ secrets.TESTNET_PRIVATE_KEY }}
        BSC_RPC_URL: ${{ secrets.BSC_RPC_URL }}
    
    - name: Test token transfers
      run: npx hardhat run scripts/test-transfers.js --network bscTestnet
      env:
        PRIVATE_KEY: ${{ secrets.TESTNET_PRIVATE_KEY }}
        BSC_RPC_URL: ${{ secrets.BSC_RPC_URL }}
        CONTRACT_ADDRESS: ${{ secrets.TESTNET_CONTRACT_ADDRESS }}
